VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puphpet/centos65-x64"

  config.vm.define :node1 do |node1| 
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "192.168.33.101"
    node1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 512]
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo sh /vagrant/setup.sh
    SHELL

  end

  config.vm.define :node2 do |node2| 
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "192.168.33.102"
    node2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 512]
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo sh /vagrant/setup.sh
    SHELL

  end

  config.vm.define :node3 do |node3|
    node3.vm.hostname = "node3"
    node3.vm.network :private_network, ip: "192.168.33.103"
    node3.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 512]
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo sh /vagrant/setup.sh
    SHELL

  end

  config.vm.define :node4 do |node4|
    node4.vm.hostname = "node4"
    node4.vm.network :private_network, ip: "192.168.33.104"
    node4.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 512]
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo sh /vagrant/setup.sh
    SHELL

  end

end
